base_url = "https://"
title = "白茶"
description = "This is an example description"
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.jpg"
theme = "toggle"              # light, dark, auto, toggle
comment = false
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/"

menu = [
    { name = "博客", url = "/posts", weight = 1 },
    { name = "标签", url = "/tags", weight = 2 },
    { name = "关于", url = "/about", weight = 3 },
]

# socials = [
#     { name = "twitter", url = "", icon = "twitter" },
#     { name = "github", url = "", icon = "github" },
# ]

custom_css = []